# Generated by Django 3.0.8 on 2020-11-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MicroTestsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
